#action.yaml
name: 'Custom Github Action'
description:'A Github Action that takes an inpur and returns the square of the number'
inputs:
  num:
    required: true
    default: "1"
outputs:
  num_squared:
    value: ${{steps.get-square.outputs.num_squared}}
runs:
  using: 'composite'
  steps: 
    -name: Install python
     uses:actions/setup-python@v4
     with:
      python-version: '3.10'
    -name: Install dedpendencies
     run: pip install -r requirements.txt
     shell: bash
    -name: Pass inputs to shell
     run:
      echo "INPUT_NUM=${{inputs.num}}" >> $GITHUB_ENV
      shell: bash
    -name: Fetch the number's square
     id: get-square
     run: python src/get_num_square.py
     shell: bash
